export const SET_CATEGORY_NAME = "SET_CATEGORY_NAME";
export const SET_CATEGORY_CODE = "SET_CATEGORY_CODE";
export const SET_CATEGORY_CONTENT = "SET_CATEGORY_CONTENT";
export const SET_CATEGORY_PARENT_ID = "SET_CATEGORY_PARENT_ID";
export const SET_EDIT_CATEGORY = "SET_EDIT_CATEGORY";
export const RESET_CATEGORY = "RESET_CATEGORY";
export const SET_ALL_CATEGORY = "SET_ALL_CATEGORY";
