export const SET_EDIT_ASSIGN_CAT_PRD = "SET_EDIT_ASSIGN_CAT_PRD";
export const SET_ASSIGNED_UNASSIGNED_CAT_PRD =
  "SET_ASSIGNED_UNASSIGNED_CAT_PRD";
export const RESET_CAT_PRD = "RESET_CAT_PRD";
export const SET_ASSIGN_CAT_ID = "SET_ASSIGN_CAT_ID";
export const SET_ASSIGN_PRD_ID = "SET_ASSIGN_PRD_ID";
