export const SET_ATTRIBUTE_PROMPT = "SET_ATTRIBUTE_PROMPT";
export const SET_ATTRIBUTE_CODE = "SET_ATTRIBUTE_CODE";
export const SET_ATTRIBUTE_LABEL = "SET_ATTRIBUTE_LABEL";
export const SET_ATTRIBUTE_TYPE = "SET_ATTRIBUTE_TYPE";
export const SET_ATTRIBUTE_IMAGE = "SET_ATTRIBUTE_IMAGE";
export const SET_ATTRIBUTE_LABEL_CODE = "SET_ATTRIBUTE_LABEL_CODE";
export const SET_EDIT_ATTRIBUTE = "SET_EDIT_ATTRIBUTE";
export const RESET_ATTRIBUTE_DATA = "RESET_ATTRIBUTE_DATA";
