export const SET_STATE_NAME = "SET_STATE_NAME";
export const SET_STATE_CODE = "SET_STATE_CODE";
export const SET_EDIT_STATE = "SET_EDIT_STATE";
export const RESET_STATE_DATA = "RESET_STATE_DATA";
export const SET_ASSIGNED_UNASSIGNED_STATE = "SET_ASSIGNED_UNASSIGNED_STATE";
