export const SET_COUNTRY_NAME = "SET_COUNTRY_NAME";
export const SET_COUNTRY_CODE = "SET_COUNTRY_CODE";
export const SET_EDIT_COUNTRY = "SET_EDIT_COUNTRY";
export const SET_DELETE_COUNTRY = "SET_DELETE_COUNTRY";
export const RESET_COUNTRY_DATA = "RESET_COUNTRY_DATA";
export const SET_STARTING_AFTER = "SET_STARTING_AFTER";
export const SET_COUNTRY_STORE = "SET_COUNTRY_STORE";
export const SET_COUNTRY_KEYWORD = "SET_COUNTRY_KEYWORD";
export const SET_TOTAL_COUNTRY = "SET_TOTAL_COUNTRY";
export const SET_COUNTRY_LIMIT = "SET_COUNTRY_LIMIT";
export const SET_ASSIGNED_UNASSIGNED_COUNTRY =
  "SET_ASSIGNED_UNASSIGNED_COUNTRY";
