export const SET_COUNTRY_NAME = "SET_COUNTRY_NAME";
export const SET_COUNTRY_CODE = "SET_COUNTRY_CODE";
export const SET_EDIT_COUNTRY = "SET_EDIT_COUNTRY";
export const RESET_COUNTRY_DATA = "RESET_COUNTRY_DATA";
export const SET_ASSIGNED_UNASSIGNED_COUNTRY =
  "SET_ASSIGNED_UNASSIGNED_COUNTRY";
